site_name: WISP
site_url: https://docs.wisp.compete-mcgill.ca
site_description: A training platform for competitive programming

repo_name: Compete McGill
repo_url: https://github.com/Compete-McGill
edit_uri: ""

nav:
    - Introduction: index.md
    - Getting Started: getting_started.md
    - Architecture: architecture.md
    - Microservices:
      - General: microservices/general.md
      - Problems: microservices/problems.md
      - Users: microservices/users.md
theme:
  name: "material"
  # logo: "img/cp-logo.svg"
  favicon: "img/cp-logo.svg"
  icon:
    logo: material/library
    repo: fontawesome/brands/github
  language: "en"
  palette:
    primary: "red"
    accent: "red"
  font:
    text: "Roboto"
    code: "Roboto Mono"

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Compete-McGill
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/competemcgill/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/CompeteMcGill/

markdown_extensions:
  - pymdownx.tabbed
  - codehilite
  - admonition