name: Lint, Test

on:
  pull_request:
    paths:
      - "e2e/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: e2e/npm ci
      - run: e2e/npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: e2e/npm ci
      - run: e2e/npm run build:image
      - run: e2e/npm run e2e